create database car_rental;

use car_rental;

Create table Dim_location(
location_key int autoincrement primary key,
location_id string unique not null,
location_name string
);

Create or replace table dim_customer(
customer_key int autoincrement primary key,
customer_id string unique not null,
name string,
email string,
phone string,
effective_date timestamp,
end_date timestamp,
is_current boolean
);

create table dim_date(
date_key int primary key,
date Date unique not null,
year int,
month int,
day int,
quarter int
);

create or replace table dim_car(
car_key int autoincrement primary key,
car_id string unique not null,
make string,
model string,
year int
);



create or replace table fact_rentals(
rental_id string primary key,
customer_key int,
car_key int,
pickup_loc_key int,
drop_loc_key int,
start_date_key int,
end_date_key int,
amount float,
quantity int,
rental_duration_days int,
total_rental_amount int,
average_rental_amount float,
is_long_rental boolean,
foreign key(customer_key) references dim_customer(customer_key),
foreign key(car_key) references dim_car(car_key),
foreign key(pickup_loc_key) references dim_date(date_key),
foreign key(drop_loc_key) references dim_date(date_key),
foreign key(start_date_key) references dim_date(date_key),
foreign key(end_date_key) references dim_date(date_key)



);



INSERT INTO dim_location (location_id, location_name) VALUES
('LOC001', 'New York - JFK Airport'),
('LOC002', 'Los Angeles - LAX Airport'),
('LOC003', 'Chicago - OHare Airport'),
('LOC004', 'Houston - Bush Intercontinental Airport'),
('LOC005', 'San Francisco - SFO Airport'),
('LOC006', 'Miami - MIA Airport'),
('LOC007', 'Seattle - SeaTac Airport'),
('LOC008', 'Atlanta - Hartsfield-Jackson Airport'),
('LOC009', 'Dallas - DFW Airport'),
('LOC010', 'Denver - DEN Airport');


INSERT INTO dim_car (car_id, make, model, year) VALUES
('CAR001', 'Toyota', 'Camry', 2020),
('CAR002', 'Honda', 'Civic', 2019),
('CAR003', 'Ford', 'Mustang', 2021),
('CAR004', 'Chevrolet', 'Impala', 2018),
('CAR005', 'Tesla', 'Model S', 2022),
('CAR006', 'BMW', '3 Series', 2021),
('CAR007', 'Audi', 'A4', 2020),
('CAR008', 'Mercedes-Benz', 'C-Class', 2019),
('CAR009', 'Volkswagen', 'Passat', 2021),
('CAR010', 'Nissan', 'Altima', 2020);


INSERT INTO dim_date (date_key, date, year, month, day, quarter) VALUES
(20240701, '2024-07-01', 2024, 7, 1, 3),
(20240702, '2024-07-02', 2024, 7, 2, 3),
(20240703, '2024-07-03', 2024, 7, 3, 3),
(20240704, '2024-07-04', 2024, 7, 4, 3),
(20240705, '2024-07-05', 2024, 7, 5, 3),
(20240706, '2024-07-06', 2024, 7, 6, 3),
(20240707, '2024-07-07', 2024, 7, 7, 3),
(20240708, '2024-07-08', 2024, 7, 8, 3),
(20240709, '2024-07-09', 2024, 7, 9, 3),
(20240710, '2024-07-10', 2024, 7, 10, 3),
(20240711, '2024-07-11', 2024, 7, 11, 3),
(20240712, '2024-07-12', 2024, 7, 12, 3),
(20240713, '2024-07-13', 2024, 7, 13, 3),
(20240714, '2024-07-14', 2024, 7, 14, 3),
(20240715, '2024-07-15', 2024, 7, 15, 3),
(20240716, '2024-07-16', 2024, 7, 16, 3),
(20240717, '2024-07-17', 2024, 7, 17, 3),
(20240718, '2024-07-18', 2024, 7, 18, 3),
(20240719, '2024-07-19', 2024, 7, 19, 3),
(20240720, '2024-07-20', 2024, 7, 20, 3),
(20240721, '2024-07-21', 2024, 7, 21, 3),
(20240722, '2024-07-22', 2024, 7, 22, 3),
(20240723, '2024-07-23', 2024, 7, 23, 3),
(20240724, '2024-07-24', 2024, 7, 24, 3),
(20240725, '2024-07-25', 2024, 7, 25, 3),
(20240726, '2024-07-26', 2024, 7, 26, 3),
(20240727, '2024-07-27', 2024, 7, 27, 3),
(20240728, '2024-07-28', 2024, 7, 28, 3),
(20240729, '2024-07-29', 2024, 7, 29, 3),
(20240730, '2024-07-30', 2024, 7, 30, 3),
(20240731, '2024-07-31', 2024, 7, 31, 3);

-- To integrate my snowflake with external storage , in this case google cloud storage

create or replace storage integration gcp_bucket_read
enabled=true
storage_provider='GCS'
storage_allowed_locations=('gcs://snowflake_projects_kishalay/car_rentals_data/customers_daily/')
type=external_stage

CREATE FILE FORMAT csv_format TYPE=csv;

--To add the necessary permissions to the service account generated by snowflake to have access to the GCS Bucket
desc integration gcp_bucket_read



--To create an external stage on top of the integration so that we can refer it in our subsequent sql statements
create or replace stage rentals
url='gcs://snowflake_projects_kishalay/car_rentals_data/customers_daily/'
storage_integration=gcp_bucket_read
file_format=(format_name=csv_format)

show stages

select * from fact_rentals
select * from dim_car
select * from dim_location

select * from dim_customer

select * from dim_date